CREATE TABLE `TracksTags` (
 `id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
 `idTrack` INT UNSIGNED NOT NULL,
 `idTag` INT UNSIGNED NOT NULL,
 `isDeleted` BOOLEAN NOT NULL DEFAULT(false),
  PRIMARY KEY (id),
  FOREIGN KEY (idTrack) REFERENCES Tracks(id),
  FOREIGN KEY (idTag) REFERENCES Tags(id)
);