version: "3.5"
services:
  nginx:
    image: nginx
    build:
      context: .
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    working_dir: /srv
    restart: unless-stopped
    networks:
      - beats_pro_proxy
      - beats-pro-db
    volumes:
      - .:/srv:ro
      - ./build/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./var/logs:/srv/var/logs/:rw

  api-beatspro:
    image: golang:latest
    build:
      context: .
    command: ["go build srv/cmd/app/main.go", "--command=./main"]
    networks:
      - beats_pro_proxy
      - beats-pro-db
    volumes:
      - ./:/srv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-beatspro.entrypoints=http"
      - "traefik.http.routers.api-beatspro.rule=Host(`api.beatspro.space`)"
      - "traefik.http.services.api-beatspro.loadbalancer.server.port=8090"
      - "traefik.docker.network=beats_pro_proxy"


networks:
  beats_pro_proxy:
    external: true
  beats-pro-db:
    external: true