version: "3.5"
services:
  nginx:
    image: nginx
    build:
      context: .
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    working_dir: /go/apiBeatsPro
    restart: unless-stopped
    networks:
      - local-space_beats_pro_proxy
      - beats-pro-internal
      - local-space_beats-pro-db
    volumes:
      - .:/go/apiBeatsPro:ro
      - ./build/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./var/logs:/srv/var/logs/:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api-beatspro
    #ports:
      #- "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-beatspro.entrypoints=http"
      - "traefik.http.routers.api-beatspro.rule=Host(`api.beatspro.space`)"
      - "traefik.http.services.api-beatspro.loadbalancer.server.port=8090"
      - "traefik.docker.network=local-space_beats_pro_proxy"

  api-beatspro:
    image: "${SERVICE_NAME}-${LOCAL_BASE_DOMAIN_SLUG}"
    build:
      context: .
      dockerfile: Dockerfile
    command: ['CompileDaemon', '--build="go build cmd/app/main.go"', "--command=./main"]
    networks:
      - local-space_beats_pro_proxy
      - beats-pro-internal
      - local-space_beats-pro-db
    volumes:
      - .:/go/apiBeatsPro
    working_dir: /go/apiBeatsPro

networks:
  local-space_beats-pro-db:
    external: true
  beats-pro-internal:
    external: false
  local-space_beats_pro_proxy:
    external: true