version: "3.5"
services:
  nginx:
    image: nginx
    build:
      context: .
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    working_dir: /go/apiBeatsPro
    restart: unless-stopped
    networks:
      - beatsprotraefik_beats_pro_proxy
      - beats-pro-internal
      - beats-pro-db
    volumes:
      - .:/go/apiBeatsPro:ro
      - ./build/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./var/logs:/srv/var/logs/:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api-beatspro
    #ports:
      #- "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-beatspro.entrypoints=http"
      - "traefik.http.routers.api-beatspro.rule=Host(`api.beatspro.space`)"
      - "traefik.http.services.api-beatspro.loadbalancer.server.port=8090"
      - "traefik.docker.network=beatsprotraefik_beats_pro_proxy"

  api-beatspro:
    image: golang:latest
    build:
      context: .
    command: "go run cmd/app/main.go"
    networks:
      - beatsprotraefik_beats_pro_proxy
      - beats-pro-internal
      - beats-pro-db
    volumes:
      - .:/go/apiBeatsPro
    working_dir: /go/apiBeatsPro
    #ports:
      #- "8855:8855"

networks:
  beats-pro-db:
    external: true
  beats-pro-internal:
    external: true
  beatsprotraefik_beats_pro_proxy:
    external: true