version: "3.5"
services:
  nginx:
    image: nginx
    build:
      context: .
      dockerfile:
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]
    working_dir: /srv
    restart: unless-stopped
    network_mode: service:go
      - go
    volumes:
      - .:/srv:ro
      - ./build/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./var/logs:/srv/var/logs/:rw

  api-beatspro:
    image: golang:latest
    build:
      context: .
      dockerfile: ./build/docker/go/Dockerfile
    networks:
      - beats_pro_proxy
      - beats-pro-db
    volumes:
      - ./:/srv
    labels:


networks:
  beats_pro_proxy:
    external: true
  beats-pro-db:
    external: true